name: TWAS KD Daily Screener

on:
  schedule:
    # 台北 13:40 = UTC 05:40，週一到週五
    - cron: "40 5 * * 1-5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy requests

      - name: Run screener
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python src/main.py
          ls -al output || true

      - name: Upload CSVs (if any)
        if: ${{ hashFiles('output/*.csv') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: picks-${{ github.run_number }}
          path: output/*.csv
