name: TWSE/TPEX KD Screener (Daily 15:00 TPE)

on:
  schedule:
    - cron: "0 7 * * *"   # 每天 07:00 UTC = 台北 15:00
  workflow_dispatch:       # 允許手動觸發

jobs:
  run-screener:
    runs-on: ubuntu-latest

    # 先把 GitHub Secrets 映射到 job 環境變數
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # 這裡用 shell 展開 env（不是 ${{ secrets.* }} 了）
      - name: Create .env for this run
        run: |
          cat > .env << EOF
          TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
          TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

          # —— 參數（可依需求調整）——
          TOP_N=20
          KD_N=9
          KD_K_SMOOTH=3
          KD_D_PERIOD=3
          KD_CROSS_WINDOW=3
          KD_REQUIRE_ZONE=false
          KD_ZONE_LOW=40
          KD_ZONE_HIGH=80

          VOLUME_LOOKBACK=20
          VOLUME_MULTIPLIER=1.5

          ENABLE_RULE_BLACK_CANDLE_LIMIT=true
          BLACK_CANDLE_MAX_DROP=0.95
          ENABLE_RULE_OC_ABOVE_MA20=true
          ENABLE_RULE_LAST5_MA10_THRESHOLD=true
          MAX_DAYS_BELOW_MA10_IN_5=3
          ENABLE_RULE_MA5_GT_MA20=true

          MARKET_CAP_MIN=10000000000
          BATCH_SIZE=120

          # 納入上櫃
          INCLUDE_TPEX=true
          EOF

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy requests python-dotenv lxml yfinance
          fi

      - name: Run screener
        run: python src/main.py

      - name: Upload CSV artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: picks-${{ github.run_id }}
          path: output/*.csv
          retention-days: 14

      # 只做顯示，檢查 env 是否帶到
      - name: Check secrets presence (masked)
        run: |
          [ -n "${TELEGRAM_BOT_TOKEN}" ] && echo "BOT_TOKEN: set" || echo "BOT_TOKEN: MISSING"
          [ -n "${TELEGRAM_CHAT_ID}" ]   && echo "CHAT_ID: set"   || echo "CHAT_ID: MISSING"

      # ✅ 重點：用 env.* 在 if: 判斷，就不會報 "Unrecognized named-value: 'secrets'"
      - name: (Test) send a Telegram ping
        if: ${{ env.TELEGRAM_BOT_TOKEN != '' && env.TELEGRAM_CHAT_ID != '' }}
        run: |
          curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="✅ GitHub Actions: Telegram 測試成功（含上櫃 .TWO）" \
            -o /dev/null -w "HTTP %{http_code}\n"
