name: TWSE-TPEX KD Screener

on:
  workflow_dispatch:        # 手動執行
  schedule:
    # GitHub Actions 使用 UTC。台北 13:40 = UTC 05:40
    - cron: "40 5 * * 1-5"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Taipei
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: src

      # === .env 參數（可調整）===
      TOP_N: "30"
      KD_N: "9"
      KD_K_SMOOTH: "3"
      KD_D_PERIOD: "3"
      KD_CROSS_WINDOW: "3"
      KD_REQUIRE_ZONE: "false"
      KD_ZONE_LOW: "40"
      KD_ZONE_HIGH: "80"
      VOLUME_LOOKBACK: "20"
      VOLUME_MULTIPLIER: "1.2"
      MIN_DAILY_VOLUME_10D: "300000"
      ENABLE_RULE_BLACK_CANDLE_LIMIT: "true"
      BLACK_CANDLE_MAX_DROP: "0.95"
      ENABLE_RULE_OC_ABOVE_MA20: "true"
      ENABLE_RULE_LAST5_MA10_THRESHOLD: "true"
      MAX_DAYS_BELOW_MA10_IN_5: "3"
      ENABLE_RULE_MA5_GT_MA20: "true"
      MARKET_CAP_MIN: "5000000000"
      BATCH_SIZE: "120"
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Render .env
        run: |
          cat > .env << 'EOF'
          TOP_N=${TOP_N}
          KD_N=${KD_N}
          KD_K_SMOOTH=${KD_K_SMOOTH}
          KD_D_PERIOD=${KD_D_PERIOD}
          KD_CROSS_WINDOW=${KD_CROSS_WINDOW}
          KD_REQUIRE_ZONE=${KD_REQUIRE_ZONE}
          KD_ZONE_LOW=${KD_ZONE_LOW}
          KD_ZONE_HIGH=${KD_ZONE_HIGH}
          VOLUME_LOOKBACK=${VOLUME_LOOKBACK}
          VOLUME_MULTIPLIER=${VOLUME_MULTIPLIER}
          MIN_DAILY_VOLUME_10D=${MIN_DAILY_VOLUME_10D}
          ENABLE_RULE_BLACK_CANDLE_LIMIT=${ENABLE_RULE_BLACK_CANDLE_LIMIT}
          BLACK_CANDLE_MAX_DROP=${BLACK_CANDLE_MAX_DROP}
          ENABLE_RULE_OC_ABOVE_MA20=${ENABLE_RULE_OC_ABOVE_MA20}
          ENABLE_RULE_LAST5_MA10_THRESHOLD=${ENABLE_RULE_LAST5_MA10_THRESHOLD}
          MAX_DAYS_BELOW_MA10_IN_5=${MAX_DAYS_BELOW_MA10_IN_5}
          ENABLE_RULE_MA5_GT_MA20=${ENABLE_RULE_MA5_GT_MA20}
          MARKET_CAP_MIN=${MARKET_CAP_MIN}
          BATCH_SIZE=${BATCH_SIZE}
          TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
          TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
          EOF

      - name: Run screener
        run: python src/main.py

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screener-artifacts
          path: |
            output/*.csv
            history/*.csv
            logs/*
          if-no-files-found: warn
